### ISSUE TITLE
Unsupported layer type: 'PeriodicShuffle'.

### ISSUE THREAD

**Issue by my1347** [Wangyupei/CED#1]
Dear Wang~
HED works fine for me. But CED has some issue. 
![image](https://user-images.githubusercontent.com/5409816/35546235-66d94276-05ae-11e8-94fa-5637842fbadf.png)
![image](https://user-images.githubusercontent.com/5409816/35546247-735b4080-05ae-11e8-9ea0-13d5658018f0.png)
Thank you so much
谢谢老铁

**Comment by pkuCactus** [comment]
Because the author have added a new layer called PeriodicShuffle

**Comment by ydzhang12345** [comment]
is the project not meant to be open-source? Cant find any details about the PeriodicShuffle layer

**Comment by Wangyupei** [comment]
We will update this project after the journal version. For PeriodShuffle, please refer to https://github.com/tetrachrome/subpixel (we have cited it and presented details in our paper). It is widely used for image super-resolution.

**Comment by kyjak** [comment]
Was this updated? Cause still getting this error while doing "make all"
