### ISSUE TITLE
Questions about CED and Res16x-CED

### ISSUE THREAD

**Issue by xavysp** [Wangyupei/CED#4]
Dear authors,
first of all, thanks for sharing your paper on arxiv and the code here. Now here is my question
I understand that CED-multi has in the upsampling  subpixel convolution and
What about CED and Res16x-CED? 
Res16x-CED uses ResNet50 architecture, so Is the architecture trained from scratch?

Thanks in advance and sorry if the questions are a little naive 

P.S. I am going to replicate in tensorflow :)

**Comment by Wangyupei** [comment]
Thanks. Res16x-CED uses ResNet50 architecture, we use the pretrained model on Imagenet.
