### ISSUE TITLE
Implementation details in ResNet50 backbone

### ISSUE THREAD

**Issue by naoto0804** [Wangyupei/CED#5]
Thanks for sharing your paper and the code.

In your TIP paper, you changed the backbone network to ResNet50. To my understanding, we get 5 feature maps downsampled by a factor of 1, 2, 4, 8, 16 from the backbone ResNet50, and then fuse them progressively with your proposed modules.  However, a first convolutional layer in ResNet50 has `stride=2`, thus producing a feature map downsampled by a factor of 2. How did you get the feature map that is not downsampled at all?

**Comment by Wangyupei** [comment]
Maybe you can set stride=1 in the first convolutional layer.

**Comment by naoto0804** [comment]
I appreciate it.
